### ISSUE TITLE
Change content parser

### ISSUE THREAD

**Issue by shuiRong** [albertincx/formatbot1#10]
[@mozilla/readability](https://github.com/mozilla/readability) is better than `@postlight/mercury-parser`

here is an example page: https://www.douban.com/people/166039423/status/3594363157/

`@mozilla/readability` can get main content but `@postlight/mercury-parser` can't.

> main content is: 
![image](https://user-images.githubusercontent.com/16076993/134517477-f6380044-911d-4f7d-a97f-75f9d3e2dea2.png)

<details>
<summary>example's source code</summary>

```js
var fs = require('fs')
var { Readability } = require('@mozilla/readability')
var Mercury = require('@postlight/mercury-parser')
var { JSDOM } = require('jsdom')

// source html is from: https://www.douban.com/people/166039423/status/3594363157/
var html = fs.readFileSync('t.html', 'utf8')

var doc = new JSDOM(html)

var reader = new Readability(doc.window.document)
var article = reader.parse()

console.log('mozilla_____', article)

Mercury.parse(
  'https://www.douban.com/people/166039423/status/3594363157/',
  {
    html,
  }
)
  .then((res) => {
    console.log('mercury_____', res)
  })
  .catch((err) => {
    console.log('mercury_____', err)
  })

```
</details>

**Comment by albertincx** [comment]
Parser works better
